### ISSUE TITLE
Add more space in nested lists

### ISSUE THREAD

**Issue by kbroman** [kbroman/kbroman.github.io#6]
See <https://kbroman.org/pages/COCpolicies.html>. Nests lists need a bit more space after

**Comment by kbroman** [comment]
Fixed in [this commit](https://github.com/kbroman/kbroman.github.io/commit/48f4cd5df96a9e27519216af9340fabf6e7fd4ed) by adding

```css
ul ul {
    margin-bottom: 20px;
}
```
